[[redirects]]
from ="/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build"
  publish = "dist"  # Adjust this if your build output directory is different

[build.environment]
  YARN_VERSION = "latest"
